# -*- coding: utf-8 -*-
"""
report_generator.py
-------------------
Generates comprehensive Markdown Weekly Channel Growth Reports and postmortems.
"""

from typing import Dict, Any, List


def generate_weekly_growth_report(
    channel_id: str,
    channel_name: str,
    video_summaries: List[Dict[str, Any]],
    experiment_results: List[Dict[str, Any]],
    recommended_topics: List[Dict[str, Any]]
) -> str:
    """
    Constructs a readable markdown report summarizing recent performance,
    experiment conclusions, and next recommended actions.
    """
    total_videos = len(video_summaries)
    if total_videos == 0:
        return f"# Weekly Growth Report: {channel_name}\n\n*No videos published in this evaluation cycle.*"

    views_list = [v["raw_24h"]["views"] for v in video_summaries]
    apv_list = [v["raw_24h"]["avg_percentage_viewed"] for v in video_summaries]

    median_views = sorted(views_list)[len(views_list) // 2]
    median_apv = sorted(apv_list)[len(apv_list) // 2]

    # Best & worst by composite score
    sorted_vids = sorted(video_summaries, key=lambda x: x["normalized"]["composite_performance_score"], reverse=True)
    best_vid = sorted_vids[0]
    worst_vid = sorted_vids[-1]

    md = []
    md.append(f"# 📊 Weekly Channel Growth Report — {channel_name}")
    md.append(f"**Channel ID:** `{channel_id}` | **Videos Evaluated:** {total_videos}\n")
    md.append("## 📈 1. Performance Overview")
    md.append(f"- **Median 24h Views:** {median_views:,}")
    md.append(f"- **Median Average Percentage Viewed (APV):** {median_apv:.1f}%")
    md.append(f"- **Top Video:** `{best_vid['video_id']}` (Score: {best_vid['normalized']['composite_performance_score']})")
    md.append(f"- **Lowest Video:** `{worst_vid['video_id']}` (Score: {worst_vid['normalized']['composite_performance_score']})\n")

    md.append("## 🧪 2. Active Experiment Outcomes")
    if experiment_results:
        for exp in experiment_results:
            md.append(f"- **{exp.get('experiment_id')}:** {exp.get('verdict')} (Decision: `{exp.get('decision')}`, Confidence: `{exp.get('confidence')}`)")
            md.append(f"  *Hypothesis:* {exp.get('hypothesis')}")
    else:
        md.append("- *No completed experiments in this cycle (data gathering in progress).*\n")

    md.append("\n## 🎯 3. Recommended Next Topics (Top Ranked)")
    for i, t in enumerate(recommended_topics[:5], 1):
        md.append(f"{i}. **{t.get('topic')}** (Score: {t.get('score')}) — *{t.get('reason')}*")

    md.append("\n---\n*Report generated by Autonomous Content Intelligence Engine.*")
    return "\n".join(md)
